spring:
  application:
    name: samples-sql-injection

  datasource:
    url: jdbc:postgresql://localhost:5432/playground?currentSchema=sqlinjection&reWriteBatchedInserts=true
    username: postgres
    password: admin

  jpa:
    properties:
      hibernate:
        default_schema: "sqlinjection"
        hbm2ddl:
          auto: none

logging:
  level:
    hipravin.samples: DEBUG
    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.type.descriptor.sql: TRACE #prior to hibernate 6
    org.springframework: DEBUG
#    org.springframework: INFO
    org.postgresql: TRACE
